### ISSUE TITLE
targetdist_annotation_v0_1.tar.bz2

### ISSUE THREAD

**Issue by xucaoling** [dmaticzka/targetdist#1]
Hi

I want to download  annotation file from http://www.bioinf.uni-freiburg.de/~maticzkd/targetdist_annotation_v0_1.tar.bz2, but it can not open now, Could you share it with me

Thank you!

**Comment by dmaticzka** [comment]
Hey,
My former employer appears to have deleted the files. Unfortunately I don't have access to this data anymore, please excuse the inconvenience. I will archive this project.
Best
Daniel
